var isocountries =
{
	'US':'United States',
	'GB':'United Kingdom',
	'CA':'Canada',
	'AF':'Afghanistan',
	'AL':'Albania',
	'DZ':'Algeria',
	'AS':'American Samoa',
	'AD':'Andorra',
	'AO':'Angola',
	'AI':'Anguilla',
	'AQ':'Antarctica',
	'AG':'Antigua and Barbuda',
	'AR':'Argentina',
	'AM':'Armenia',
	'AW':'Aruba',
	'AU':'Australia',
	'AT':'Austria',
	'AZ':'Azerbaijan',
	'BS':'Bahamas',
	'BH':'Bahrain',
	'BD':'Bangladesh',
	'BB':'Barbados',
	'BY':'Belarus',
	'BE':'Belgium',
	'BZ':'Belize',
	'BJ':'Benin',
	'BM':'Bermuda',
	'BT':'Bhutan',
	'BO':'Bolivia',
	'BA':'Bosnia And Herzegowina',
	'BW':'Botswana',
	'BV':'Bouvet Island',
	'BR':'Brazil',
	'IO':'British Indian Ocean Territory',
	'BN':'Brunei Darussalam',
	'BG':'Bulgaria',
	'BF':'Burkina Faso',
	'BI':'Burundi',
	'KH':'Cambodia',
	'CM':'Cameroon',
	'CV':'Cape Verde',
	'KY':'Cayman Islands',
	'CF':'Central African Republic',
	'TD':'Chad',
	'CL':'Chile',
	'CN':'China',
	'CX':'Christmas Island',
	'CC':'Cocos(Keeling)Islands',
	'CO':'Colombia',
	'KM':'Comoros',
	'CG':'Congo',
	'CK':'Cook Islands',
	'CR':'Costa Rica',
	'CI':'Cote D\'Ivoire',
	'HR':'Croatia',
	'CU':'Cuba',
	'CY':'Cyprus',
	'CZ':'Czech Republic',
	'DK':'Denmark',
	'DJ':'Djibouti',
	'DM':'Dominica',
	'DO':'Dominican Republic',
	'TP':'East Timor',
	'EC':'Ecuador',
	'EG':'Egypt',
	'SV':'El Salvador',
	'GQ':'Equatorial Guinea',
	'ER':'Eritrea',
	'EE':'Estonia',
	'ET':'Ethiopia',
	'FK':'Falkland Islands',
	'FO':'Faroe Islands',
	'FJ':'Fiji',
	'FI':'Finland',
	'FR':'France',
	'FX':'France Metropolitan',
	'GF':'French Guiana',
	'PF':'French Polynesia',
	'TF':'French Southern Territories',
	'GA':'Gabon',
	'GM':'Gambia',
	'GE':'Georgia',
	'DE':'Germany',
	'GH':'Ghana',
	'GI':'Gibraltar',
	'GR':'Greece',
	'GL':'Greenland',
	'GD':'Grenada',
	'GP':'Guadeloupe',
	'GU':'Guam',
	'GT':'Guatemala',
	'GN':'Guinea',
	'GW':'Guinea-Bissau',
	'GY':'Guyana',
	'HT':'Haiti',
	'HN':'Honduras',
	'HK':'Hong Kong',
	'HU':'Hungary',
	'IS':'Iceland',
	'IN':'India',
	'ID':'Indonesia',
	'IR':'Iran',
	'IE':'Ireland',
	'IL':'Israel',
	'IT':'Italy',
	'JM':'Jamaica',
	'JP':'Japan',
	'JO':'Jordan',
	'KZ':'Kazakhstan',
	'KE':'Kenya',
	'KI':'Kiribati',
	'KW':'Kuwait',
	'KG':'Kyrgyzstan',
	'LA':'Lao People\'s Republic',
	'LV':'Latvia',
	'LB':'Lebanon',
	'LS':'Lesotho',
	'LR':'Liberia',
	'LY':'Libyan Arab Jamahiriya',
	'LI':'Liechtenstein',
	'LT':'Lithuania',
	'LU':'Luxembourg',
	'MO':'Macau',
	'MK':'Macedonia',
	'MG':'Madagascar',
	'MW':'Malawi',
	'MY':'Malaysia',
	'MV':'Maldives',
	'ML':'Mali',
	'MT':'Malta',
	'MH':'Marshall Islands',
	'MQ':'Martinique',
	'MR':'Mauritania',
	'MU':'Mauritius',
	'YT':'Mayotte',
	'MX':'Mexico',
	'FM':'Micronesia',
	'MD':'Moldova',
	'MC':'Monaco',
	'MN':'Mongolia',
	'MS':'Montserrat',
	'MA':'Morocco',
	'MZ':'Mozambique',
	'MM':'Myanmar',
	'NA':'Namibia',
	'NR':'Nauru',
	'NP':'Nepal',
	'NL':'Netherlands',
	'AN':'Netherlands Antilles',
	'NC':'New Caledonia',
	'NZ':'New Zealand',
	'NI':'Nicaragua',
	'NE':'Niger',
	'NG':'Nigeria',
	'NU':'Niue',
	'NF':'Norfolk Island',
	'KP':'North Korea',
	'MP':'Northern Mariana Islands',
	'NO':'Norway',
	'OM':'Oman',
	'PK':'Pakistan',
	'PW':'Palau',
	'PA':'Panama',
	'PG':'Papua New Guinea',
	'PY':'Paraguay',
	'PE':'Peru',
	'PH':'Philippines',
	'PN':'Pitcairn',
	'PL':'Poland',
	'PT':'Portugal',
	'PR':'Puerto Rico',
	'QA':'Qatar',
	'RE':'Reunion',
	'RO':'Romania',
	'RU':'Russian Federation',
	'RW':'Rwanda',
	'KN':'Saint Kitts And Nevis',
	'LC':'Saint Lucia',
	'VC':'Saint Vincent And The Grenadines??Unknown',
	'SM':'San Marino',
	'ST':'Sao Tome And Principe',
	'SA':'Saudi Arabia',
	'SN':'Senegal',
	'SC':'Seychelles',
	'SL':'Sierra Leone',
	'SG':'Singapore',
	'SK':'Slovakia',
	'SI':'Slovenia',
	'SB':'Solomon Islands',
	'SO':'Somalia',
	'ZA':'South Africa',
	'GS':'South Georgia/South Sandwich Islands',
	'KR':'South Korea(Republic Of Korea)',
	'ES':'Spain',
	'LK':'Sri Lanka',
	'SH':'St Helena',
	'PM':'St Pierre and Miquelon',
	'SD':'Sudan',
	'SR':'Suriname',
	'SJ':'Svalbard And Jan Mayen Islands',
	'SZ':'Swaziland',
	'SE':'Sweden',
	'CH':'Switzerland',
	'SY':'Syrian Arab Republic',
	'TW':'Taiwan',
	'TJ':'Tajikistan',
	'TZ':'Tanzania',
	'TH':'Thailand',
	'TG':'Togo',
	'TK':'Tokelau',
	'TO':'Tonga',
	'TT':'Trinidad And Tobago',
	'TN':'Tunisia',
	'TR':'Turkey',
	'TM':'Turkmenistan',
	'TC':'Turks And Caicos Islands',
	'TV':'Tuvalu',
	'UG':'Uganda',
	'UA':'Ukraine',
	'AE':'United Arab Emirates',
	'UM':'U.S.Minor Outlying Islands',
	'UY':'Uruguay',
	'UZ':'Uzbekistan',
	'VU':'Vanuatu',
	'VA':'Vatican City State',
	'VE':'Venezuela',
	'VN':'Viet Nam',
	'VG':'Virgin Islands(British)',
	'VI':'Virgin Islands(U.S.)',
	'WF':'Wallis And Futuna Islands',
	'EH':'Western Sahara',
	'YE':'Yemen',
	'ZR':'Zaire',
	'ZM':'Zambia',
	'ZW':'Zimbabwe',
	'PS':'Palestine',
	'SS':'South Sudan',
	'AP':'African Regional Ind.Property organization',
	'WS':'Samoa',
	'IQ':'Iraq',
	'CD':'Congo',
	'RS':'Serbia',
	'AX':'Aaland Islands',
	'ME':'Montenegro',
	'GG':'Guernsey',
	'JE':'Jersey',
	'IM':'Isle of Man',
	'MF':'Saint Martin',
	'TL':'East Timor'
};